### ISSUE TITLE
Wipe First Flag

### ISSUE THREAD

**Issue by billsey** [jeffeb3/sandify#65]
I envision a checkmark on the Sandify page that tells the gcode to do a wipe of the table before starting on the drawing. Though maybe it should be a named wipe, so you can choose a circle wipe before an angular drawing...

**Comment by jeffeb3** [comment]
Hmmm. I don't like this very much. Mostly because it doesn't work well with the architecture so far. Things like reversing the path won't work if you have a bunch of wiper vertices at the beginning. The wiper tab really only works to clean from the outside to the outside. It doesn't end in the center either. You'd need a circle from the outside to the inside to get to the center.

One thing I was thinking about that I haven't quite got my head around is you create a pattern, then somehow put it into a list and make another one. The machine preview would show the previous path as gray or something, with the yellow being the one you're editing. I think I could make the list of patterns dynamic, and when you saved them, they would all be concatenated.

**Comment by billsey** [comment]
I pretty much think there should only be two types of start or stop parameters (0,0 and midpoint) and everything goes from 0,0 to 0,0; 0,0 to midpoint; midpoint to midpoint; or midpoint to 0,0. Midpoint should be calculated by using the table parameters before anything else is rendered. The wipe flag just does a wipe then ignores the wipe movements in order to draw the next object. It's just a shortcut to manually embedding a specific wipe in before rendering a pattern.

**Comment by mrehorst** [comment]
I have a rectangular table, so I'm not sure if this comment applies to circular tables/mechanisms.  In the past I generated wipes that started at the center and spiraled outward using a small circle with the grow and spin parameters set to appropriate values and the rotation set to zero.  Of course, you can wipe from the outside to the center by using the reverse gcode.

![image](https://user-images.githubusercontent.com/17105029/50423554-a1501f80-081c-11e9-92bf-44ed7f860f1e.png)

Be careful of spiral wipes- if you always use center to outside wipe, after a few wipes the sand will be pushed to the outside edges of the table.   Using edge to center wipe will tend to pile the sand up at the center of the table.  Alternating wipes from center to outside and outside to center helps prevent both problems.

**Comment by jeffeb3** [comment]
You can approximate this with a circle, choose a small initial size, grow, and lots of loops.

**Comment by jeffeb3** [comment]
Closing this. I think I've captured good solutions in these other issues.
