### ISSUE TITLE
Machine setting for ball size

### ISSUE THREAD

**Issue by jexoteric** [jeffeb3/sandify#78]
Could a setting be added for the ball size the machine is using with a default to 12.7mm (1/2"), as I think most people are using that size, and then use this setting to drive the size of the red and green preview dots? This would visually help users see the scale of their design path better, so if you are trying to get the tracks to line up at certain intervals, there is less guess work since many of the modifier units are ambiguous (from what I have read elsewhere the ambiguity is intentional correct?)?

Another option could be to add faint adjustable grid to the preview, but I think that would add more clutter than is necessary.

**Comment by jeffeb3** [comment]
The ambiguity in units is by necessity, since the polar machines are unitless, and grbl might be in inches.

The size of the endpoints wasn't meant to be the ball, but I guess that would make sense. If you had an enormous machine, they might be harder to find. I really intended them only as a begin and end marker.

The dots are actually pretty close to 1/2" on my screen already. The easiest way to tell is to look at the wiper tab, since it lets you give exact dimensions between rows. The dots on my screen see to be pretty close to the width of a line (but like I said, it's not absolute).
